// import './js/module-1-1.js'
// import './js/module-1-2.js'
// import './js/autocheck.js'
// import './js/module-2-1-arrays.js'
// import './js/module-2-2-functions.js'
// import './js/module-3-1.js'
// import './js/module-4-1-callback.js'
// import './js/module-4-2-iterating-array-methods.js'
// import './js/module-5-1-this.js'
// import './js/module-5-2-oop-proto-classes.js'
// import './js/module-6-1-DOM.js'
import './js/module-6-2-Event.js'
// import './js/counter.js'